version: '3.8'

services:
  app:
    image: quiz-game:latest
    container_name: quiz-game
    ports:
      - '3000:3000'
    environment:
      - MONGO_URI=mongodb://mongo:27017/quizgame
      - JWT_SECRET=${JWT_SECRET:-$(openssl rand -hex 16)}
    depends_on:
      - mongo
    restart: always

  mongo:
    image: mongo:5.0
    container_name: mongodb
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db
    restart: always

volumes:
  mongo-data:
    driver: local
