apiVersion: apps/v1
kind: Deployment
metadata:
  name: quiz-game
  labels:
    app: quiz-game
spec:
  replicas: 2
  selector:
    matchLabels:
      app: quiz-game
  template:
    metadata:
      labels:
        app: quiz-game
    spec:
      containers:
        - name: quiz-game
          image: nilava99/quiz-game:latest 
          ports:
            - containerPort: 3000
          env:
            - name: MONGO_URI
              value: "mongodb://mongodb-service:27017/quizgame"
            - name: JWT_SECRET
              value: "NiuZsaSgB2oPUYQD0ivhaTINQMrQCsGMImC3qEE33vH3emaCDBqGbXVi0KWuS8QS6yPanArfoDe8IP2or5atLlZy7YGJesNmyuM"
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: quiz-game-service
spec:
  type: LoadBalancer
  selector:
    app: quiz-game
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000      
      # nodePort: 30001        
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  labels:
    app: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo:5.0
          ports:
            - containerPort: 27017
          volumeMounts:
            - mountPath: /data/db
              name: mongo-persistent-storage
          resources:
            requests:
              memory: "256Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1"
      volumes:
        - name: mongo-persistent-storage
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
spec:
  type: ClusterIP
  selector:
    app: mongodb
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017      
      # nodePort: 30001    